#!/bin/bash

# This script runs the same pytests that are run on CircleCI,
# in the same Docker container.

# For the code that is directly run on CircleCI, see
# `.circleci/config.yml`.

# See `scripts/test_build_deploy.sh` for the BuildKite testing suite.
# Eventually, we will want to move all BuildKite testing functionality to
# CircleCI. (In the process of migrating).

img_name="ghcr.io/minerllabs/minerl"

docker build -t $img_name .
docker run --rm -it $img_name pytest
